<?xml version="1.0"?>
<package format="3">
  <name>global_relocalization_kiss_matcher</name>
  <version>0.1.0</version>
  <description>KISS-Matcher global initialization with small_gicp continuous relocalization.</description>
  <maintainer email="liyuminglyx@163.com">pio</maintainer>

  <license>MIT license</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>pcl_conversions</depend>
  <depend>eigen</depend>
  <depend>libflann-dev</depend>
  <depend>libomp-dev</depend>
  <depend>libpcl-all-dev</depend>
  <depend>tbb</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
